"""add extracted text to resumes

Revision ID: 8c8dad32a5e5
Revises: ff89838a5fef
Create Date: 2026-08-18 17:40:21.258919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8dad32a5e5'
down_revision = 'ff89838a5fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_job_apps_search'), postgresql_ops={"lower((((job_title::text || ' '::text) || company_name::text) || ' '::text) || COALESCE(job_location, ''::character varying)::text)": 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index('idx_job_apps_search', [sa.literal_column("lower(job_title || ' ' || company_name || ' ' || COALESCE(job_location, ''))").label('job_apps_search_expr')], unique=False, postgresql_ops={'job_apps_search_expr': 'gin_trgm_ops'}, postgresql_using='gin')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('extracted_text')

    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_index('idx_job_apps_search', postgresql_ops={'job_apps_search_expr': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_job_apps_search'), [sa.literal_column("lower((((job_title::text || ' '::text) || company_name::text) || ' '::text) || COALESCE(job_location, ''::character varying)::text)")], unique=False, postgresql_ops={"lower((((job_title::text || ' '::text) || company_name::text) || ' '::text) || COALESCE(job_location, ''::character varying)::text)": 'gin_trgm_ops'}, postgresql_using='gin')

    # ### end Alembic commands ###
