"""Align models with database schema

Revision ID: ff89838a5fef
Revises: 
Create Date: 2026-07-23 22:33:25.542835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff89838a5fef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_job_apps_search'), postgresql_ops={"lower((((job_title::text || ' '::text) || company_name::text) || ' '::text) || COALESCE(job_location, ''::character varying)::text)": 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index('idx_job_apps_search', [sa.literal_column("lower(job_title || ' ' || company_name || ' ' || COALESCE(job_location, ''))").label('job_apps_search_expr')], unique=False, postgresql_ops={'job_apps_search_expr': 'gin_trgm_ops'}, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_index('idx_job_apps_search', postgresql_ops={'job_apps_search_expr': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_job_apps_search'), [sa.literal_column("lower((((job_title::text || ' '::text) || company_name::text) || ' '::text) || COALESCE(job_location, ''::character varying)::text)")], unique=False, postgresql_ops={"lower((((job_title::text || ' '::text) || company_name::text) || ' '::text) || COALESCE(job_location, ''::character varying)::text)": 'gin_trgm_ops'}, postgresql_using='gin')

    # ### end Alembic commands ###
